### ISSUE TITLE
Interface in C/C++ for accessing Altstring/Altrep data

### ISSUE THREAD

**Issue by traversc** [tidyverse/vroom#250]
For accessing the underlying string data, I believe the only option is `STRING_ELT` or the analogous Rcpp methods. However, that causes materialization, which as you know is costly. 

If there were a way to access the data (e.g. a C-style string `const char *` and the encoding `cetype_t`) I think that would be a good way for users and package developers to fully take advantage of the Altstring implementation in vroom.

**Comment by jimhester** [comment]
So in this scenario vroom would provide a header with methods that 3rd parties could use? One complication is that it couldn't be a `const char *`, as fields are not guaranteed to be null terminated, it would have to be a `vroom::string()` object.

Also the locale would not be trivial to handle, vroom internally converts strings to UTF-8 when it creates the CHARSXP objects, but before this the character data could be in any supported locale. A third party package would have to either do the same conversion to CHARSXP (in which case they might as well just use `STRING_ELT()`) or provide some other way to convert the data.

**Comment by traversc** [comment]
I think those conversions would be fine for vroom to handle internally, I see the `Iconv` class has a method that returns `std::string` (`std::string Iconv::makeString`). 

I think various interfaces like the following would be nice:

```
std::pair<std::string, bool> // bool to notify if string is NA
get_vroom_string(void * vroom_data, // result of R_ExternalPtrAddr(R_altrep_data1(vec))
                           size_t i);

SEXP get_vroom_string(void * vroom_data, size_t i);
```

Alternatively, a helper function telling the third party the locale/encoding information or an iconv buffer from `Riconv_open` itself:

```
void * get_vroom_iconv(void* vroom_data); // returns an iconv object to properly convert strings

vroom::string get_vroom_string(void * vroom_data, size_t i);
```
etc.
