### ISSUE TITLE
Add rowname option

### ISSUE THREAD

**Issue by liutiming** [tidyverse/vroom#366]
Thanks for thisgreat package!

Similar to https://github.com/r-lib/vroom/issues/222 that has been closed. 

Although tidy data do not have row names, not all data in the wild are tidy. The suggested `tibble::column_to_rownames` is not sufficient because when reading a table whose first column is row name, the last column will be dropped, and the first column's name will be used as the rowname's column name, second column's name will be used as the first column name, so on and so forth.

**Comment by sbearrows** [comment]
I'm not able to reproduce this issue. If you continue having problems with `tibble::column_to_rownames()` you might consider opening an issue in that repo but we are not currently planning on supporting rownames for the vroom package.

Here is an example of using a column to set rownames using `tibble::column_to_rownames()` and the vroom package:

``` r
library(vroom)
plants <- vroom('rownames,x,y
                 tree,2,6
                 flower,5,8
                 bush,9,3',
                delim = ",",
                show_col_types = FALSE)
plants
#> # A tibble: 3 × 3
#>   rownames     x     y
#>   <chr>    <dbl> <dbl>
#> 1 tree         2     6
#> 2 flower       5     8
#> 3 bush         9     3
tibble::column_to_rownames(plants, var = "rownames")
#>        x y
#> tree   2 6
#> flower 5 8
#> bush   9 3
```

<sup>Created on 2022-03-31 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
