### ISSUE TITLE
`format_csv` segfaults with empty data frame

### ISSUE THREAD

**Issue by slwu89** [tidyverse/vroom#425]
Hi readr team,

I noticed that passing a data.frame with 0 rows/cols causes a segfault. I think it would be nice to check for this, perhaps in `format_delim` right after the call to check that `is.data.frame(x)` and return an empty string in that case, since in some cases (like mine) I'm using it programmatically to deal with incoming data and there might be genuine empty records, so downstream processing can take care of the empty csv.

I am using readr version 2.1.2 with R version 4.0.4.

```r
> library(readr)
> readr::format_csv(data.frame())

 *** caught segfault ***
address 0xffffffffffffffff, cause 'memory not mapped'
```

**Comment by jennybc** [comment]
I opened #430 for what @hindrek is reporting and will hide that comment.
