### ISSUE TITLE
Make `vroom::problems()` work more like `readr::problems()`

### ISSUE THREAD

**Issue by jennybc** [tidyverse/vroom#443]
Seems like `vroom::problems()` could also consult `.Last.value` in the case of a missing primary input, as `readr::problems()` does.

https://github.com/tidyverse/readr/blob/5ac729aa9a70fef297a634d2332ff8ff1af874fb/R/problems.R#L24-L45

Seems like there should be more assessment of whether the input was explicitly provided or not. I think you'd want a higher level of skepticism / strictness for implicit input `.Last.value` than for explicitly passed input. 

There will be several matters to think through here, around the co-existence and relationship between `readr::problems()` and `vroom::problems()`.

**Comment by sbearrows** [comment]
I think this was meant to be closed with #446

@jennybc Do you think everything here was covered with that PR?
