### ISSUE TITLE
Update test for `problems()` `unwind::protect` error

### ISSUE THREAD

**Issue by sbearrows** [tidyverse/vroom#445]
The test in question: https://github.com/tidyverse/vroom/blob/f21f3143f659745b06452ec8235819ca098fb2b0/tests/testthat/test-problems.R#L149-L172

In a PR to update the warning message from `problems()` we attempted to use `cpp11::package()` to call `cli::cli_warn()`. For a number of reasons this isn't a great idea and can actually crash R https://github.com/tidyverse/vroom/pull/441#discussion_r883611090

At the time we wrote the test, we didn't fully understand the circumstances that caused the crash. Now that we are more aware of how it occurs, we should update the test to reflect this information.

**Comment by DavisVaughan** [comment]
See https://github.com/r-lib/cpp11/issues/274 for full details of the crash
