### ISSUE TITLE
Don't inherit docs for vroom from readr

### ISSUE THREAD

**Issue by sbearrows** [tidyverse/vroom#461]
Since much of readr is implemented using vroom, it would make more sense to have readr inherit docs from vroom, rather than vroom inheriting docs from readr. We will need to fill in some gaps but we should also update some of the docs in vroom as some of them can be a bit sparse compared to readr:
https://github.com/tidyverse/readr/blob/85cf1e8e664e2a75eba393f91d89b39060140dab/R/source.R#L3-L17
https://github.com/tidyverse/vroom/blob/339073c4fc5cfdcbeb29ff716d41c2aaaf6bad43/R/vroom.R#L8

**Comment by jennybc** [comment]
A discussion on readr points out that another argument that needs attention is `lazy`.

https://github.com/tidyverse/readr/pull/1400#issuecomment-1235350960

Like `col_select` this feature is only supported in readr in 2e / via vroom. However, unlike `col_select`, the argument name and default value differs between readr 2e's usage (`lazy = FALSE`) and vroom's (`altrep = TRUE`). So readr can't simply inherit docs from vroom. I think vroom should have the detailed docs on `altrep`. In readr `lazy` can have a short explanation and refer to user to learn more in vroom if they wish to set `lazy = FALSE`.
