### ISSUE TITLE
columns in different order in multiple file read_csv

### ISSUE THREAD

**Issue by ahcyip** [tidyverse/vroom#464]
when data in different csv's have the same columns but in a different order, read_csv fails to read the data, saying the columns are different (even if total number and names match up). Would it make sense to make this a little more flexible and allow reading of csvs that do have the same columns (just in a different order)?

**Comment by sbearrows** [comment]
Thanks for opening this issue! Although this idea has merit, this feature would require substantial changes to vroom, which we do not currently have the bandwidth for.

**Comment by sbearrows** [comment]
@ahcyip Here is one way to import multiple files with the same column names, but in different orders by using `purrr::map_df`. 

``` r
library(vroom)

tf1 <- withr::local_tempfile(lines = "x,y\n1,a\n2,b\n")
tf2 <- withr::local_tempfile(lines = "y,x\nc,3\nd,4\n")

purrr::map_df(c(tf1, tf2), vroom, show_col_types = FALSE)
#> # A tibble: 4 × 2
#>       x y    
#>   <dbl> <chr>
#> 1     1 a    
#> 2     2 b    
#> 3     3 c    
#> 4     4 d
```

<sup>Created on 2022-09-06 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

**Comment by ahcyip** [comment]
That makes sense, thanks!
