### ISSUE TITLE
Error while reading zip file

### ISSUE THREAD

**Issue by Haridut** [tidyverse/vroom#475]
I'm trying to read in a huge zip file and I have tried both in mac and windows. Below is the code and error. Can you please let me know what this means and how to fix it. Zip file has a single file by the way.  More details: When I try to read in command line I do get this prompt too: [ERRO] parse error on line 1, column 15: bare " in non-quoted-field

<img width="586" alt="Screen Shot 2022-10-27 at 11 50 43 AM" src="https://user-images.githubusercontent.com/20578797/198340747-b1c0f96c-d361-4427-ac63-2a4ec1744a5a.png">

**Comment by hadley** [comment]
I would suggest you manually unzip the file. That will at least eliminating a zipping problem from the equation.
