### ISSUE TITLE
lazy reading not reading all rows and other issues

### ISSUE THREAD

**Issue by ahcyip** [tidyverse/vroom#481]
when running 
```
read_csv("c:/users/ayip/downloads/abc.csv", lazy = TRUE)
```
on a 15 GB file,
it takes a while doing the indexing, the progress meter gets stuck at "2.15GB", it uses as much RAM as the whole dataset (but at least it clears after a while and isn't stuck in the environment)
but the main issue is that I get a different number of rows sometimes:
Rows: 71M Columns: 29
Rows: 36M Columns: 29
# Rows: 118326225 Columns: 29 (this one appears to be the correct number but I'm now also seeing data shifted to wrong columns - not sure if the reading process corrupted the data or if my input data was bad)

I'm not sure if these are all known issues and I don't know how to create a reprex without the confidential data...

**Comment by jennybc** [comment]
>  I don't know how to create a reprex without the confidential data...

That will indeed be a showstopper in terms of preventing investigation.
