### ISSUE TITLE
Edition 2 reading missing factor rows as empty strings

### ISSUE THREAD

**Issue by Raesu** [tidyverse/vroom#487]
I am trying to migrate to edition 2, but there's an issue when reading in factors using the `col_types='f'` argument.

With edition 1, missing values in factor columns were read in as `NA` as expected. In edition 2, they are read in as empty strings, `""`. Reprex below. I have not seen any documentation of this change and it has made my downstream code totally fail. Adding a mutate to add missing values does not seem like the right solution.

```r
# Expected output
with_edition(1,
read_csv('alpha,bravo,charlie
         agree,,satisfied
         neutral,,dissatisfied', col_types='fff'))

# Edition 2 output
read_csv('alpha,bravo,charlie
         agree,,satisfied
         neutral,,dissatisfied', col_types='fff')
```

**Comment by Raesu** [comment]
I actually tried the above code on my Mac and it is working as expected (edition 1 and 2 outputs are the same).

I previously was running this on a Windows 10 machine.

**Comment by hadley** [comment]
This looks ok to me too:

``` r
library(readr)

# Expected output
with_edition(1,
read_csv('alpha,bravo,charlie
         agree,,satisfied
         neutral,,dissatisfied', col_types='fff'))
#> # A tibble: 2 × 3
#>   alpha   bravo charlie     
#>   <fct>   <fct> <fct>       
#> 1 agree   <NA>  satisfied   
#> 2 neutral <NA>  dissatisfied

# Edition 2 output
read_csv('alpha,bravo,charlie
         agree,,satisfied
         neutral,,dissatisfied', col_types='fff')
#> # A tibble: 2 × 3
#>   alpha   bravo charlie     
#>   <fct>   <fct> <fct>       
#> 1 agree   <NA>  satisfied   
#> 2 neutral <NA>  dissatisfied
```

<sup>Created on 2023-08-01 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
