### ISSUE TITLE
Print data to stdout in shell

### ISSUE THREAD

**Issue by NJU-Bio-Info** [tidyverse/vroom#493]
Hi, I want to use `vroom_write()` to write output to stdout in shell by using R script and the command is:
```
vroom_write(join.data, stdout(), col_names = FALSE, delim = args$delimiter)
```
but when use pipeline in shell:
```
rscript.r [arguments to scripts] | less -S
```
it gave me a error information:
```
Error in vroom_write_connection_(x, file, delim, eol, na_str = na, col_names = col_names,  :
  ignoring SIGPIPE signal
Calls: vroom_write -> vroom_write_connection_
Execution halted
```
But the result is right, I guess I can not use `less -S` in shell to preview the result. So do you have some advice for me to turn off this message?

**Comment by hadley** [comment]
We don't, sorry.
