### ISSUE TITLE
Segfault is appearing in vroom in other package's revdep checks

### ISSUE THREAD

**Issue by jennybc** [tidyverse/vroom#510]
... and in vroom's CI 😬

**Comment by jeroen** [comment]
The problem disappears when we downgrade cpp11: https://github.com/tidyverse/vroom/pull/511

This might indicate one of two problems: either a bug in cpp11, or a conflict that appears when multiple R packages are loaded which are built against different, incompatible versions of cpp11.

The latter can be ruled out by checking the latest vroom on Linux when building all packages from source (i.e. disable p3m).

**Comment by DavisVaughan** [comment]
I would guess we can rule out an ABI change because `ubuntu-release (devel)` builds all packages from source and still fails https://github.com/tidyverse/vroom/actions/runs/6214248706/job/16866006817

Haven't been able to reproduce on mac though

**Comment by DavisVaughan** [comment]
I am fairly certain i have tracked it down to https://github.com/r-lib/cpp11/commit/fe152114c01a4478e9dbd46c962c086c688ee45e, but i still don't know exactly what is wrong

**Comment by jeroen** [comment]
Thanks for fixing this @jennybc @DavisVaughan !

**Comment by jennybc** [comment]
It’s all @DavisVaughan! I’ll do a release soon.
